version: "3.9"

services:

    #application
    app:
        image: ${PROJECT_NAME}-img
        container_name: ${PROJECT_NAME}-app
        build:
            context: .
            dockerfile: ./config/php/Dockerfile
        restart: unless-stopped
        env_file: ../.env
        environment:
            #XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_STORM_PORT} remote_enable=1
            #PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        depends_on:
            - nginx
        working_dir: /var/www
        volumes:
            - ../:/var/www
            - ./config/php/conf.d:/usr/local/etc/php/conf.d
        #- ./config/php:/usr/local/etc/php
        networks:
            - app-network
        ports:
            - "9000:9000"

    #webserver
    nginx:
        image: ${PROJECT_NAME}-nginx-img
        container_name: ${PROJECT_NAME}-nginx
        build:
            context: .
            dockerfile: ./config/nginx/Dockerfile
        env_file: ../.env
        restart: unless-stopped
        volumes:
            - ../public:/var/www/public
            - ./config/nginx:/etc/nginx/conf.d
            - ./logs:/var/log/nginx/
        networks:
            - app-network
        ports:
            - "8098:80"

#Docker Networks
networks:
    app-network:
        driver: bridge
